# Created by: Jaap Boender <jaapb@kerguelen.org>
# $FreeBSD: head/devel/ocaml-calendar/Makefile 349292 2014-03-26 20:46:03Z antoine $

PORTNAME=	calendar
PORTVERSION=	2.03.2
CATEGORIES=	devel
MASTER_SITES=	http://forge.ocamlcore.org/frs/download.php/915/
PKGNAMEPREFIX=	ocaml-

MAINTAINER=	jaapb@kerguelen.org
COMMENT=	A date and time library for OCaml

NO_STAGE=	yes

GNU_CONFIGURE=	yes
USES=		gmake
USE_OCAML=	yes
USE_OCAML_FINDLIB=	yes
USE_OCAMLFIND_PLIST=	yes

.include <bsd.port.mk>
