# Created by: Eugene Ossintsev
# $FreeBSD: head/lang/ocaml-nox11/Makefile 361857 2014-07-15 03:42:50Z vanilla $

PORTNAME=	ocaml-nox11
CATEGORIES=	lang

MAINTAINER=	michael.grunewald@laposte.net
COMMENT=	Objective Caml compiler and programming environment (no X11)

MASTERDIR=	${.CURDIR}/../ocaml

OPTIONS_EXCLUDE=	TK X11

.include "${MASTERDIR}/Makefile"
