    COMMENT = Ports that I (michipili) maintain

    SUBDIR += caml-light
    SUBDIR += ocaml
    SUBDIR += ocaml-mode.el
    SUBDIR += ocaml-nox11
    SUBDIR += tuareg-mode.el

.include <bsd.port.subdir.mk>
