    COMMENT = Ports that I (michipili) maintain

    SUBDIR += ocaml-calendar
    SUBDIR += ocaml-camomile
    SUBDIR += ocaml-cppo
    SUBDIR += ocaml-event
    SUBDIR += omake

.include <bsd.port.subdir.mk>
